//list of valid color names
const colorsArray = [
'black',
'white',
'gray',
'silver',
'red',
'maroon',
'pink',
'magenta',
'purple',
'violet',
'blue',
'navy',
'cyan',
'aqua',
'teal',
'green',
'lime',
'olive',
'yellow',
'gold',
'orange',
'brown',
'beige',
'tan',
'salmon',
'coral',
'peach',
'lavender',
'orchid',
'turquoise',
'sky blue',
'indigo',
'azure',
'mint green',
'forest green',
'chartreuse',
'khaki',
'ivory',
'mauve',
'lilac',
'plum',
'fuchsia',
'hot pink',
'crimson',
'slate gray',
'steel blue',
'olive green',
'dark red',
'dark blue',
'dark green',
'tomato',
'dark cyan',
'dark slate blue',
'dark slate gray',
'dark salmon',
'dark magenta',
'dark violet',
'dark orchid',
'dark turquoise',
'dark olive green',
'dark sea green',
'dark khaki',
'dark goldenrod',
'dark orange',
'light pink',
'light magenta',
'light purple',
'light violet',
'light blue',
'light cyan',
'light aqua',
'light teal',
'light green',
'light lime',
'light olive',
'light yellow',
'light gold',
'light orange',
'light brown',
'light beige',
'light tan',
'light salmon',
'light coral',
'light peach',
'light lavender',
'light orchid',
'light turquoise',
'light sky blue',
'light indigo',
'light azure',
'light mint green',
'light forest green',
'light chartreuse',
'light khaki',
'light ivory',
'light mauve',
'light lilac',
'light plum',
'light fuchsia',
'light hot pink',
'light crimson',
'light slate gray',
'light steel blue',
'light olive green',
'light tomato',
'light dark cyan',
'light dark slate blue',
'light dark slate gray',
'light dark salmon',
'light dark magenta',
'light dark violet',
'light dark orchid',
'light dark turquoise',
'light dark olive green',
'light dark sea green',
'light dark khaki',
'light dark goldenrod',
'light dark orange',
'midnight blue',
'midnight cyan',
'midnight aqua',
'midnight teal',
'midnight green',
'midnight lime',
'midnight olive',
'midnight yellow',
'midnight gold',
'midnight orange',
'midnight brown',
'midnight beige',
'midnight tan',
'midnight salmon',
'midnight coral',
'midnight peach',
'midnight lavender',
'midnight orchid',
'midnight turquoise',
'midnight sky blue',
'midnight indigo',
'midnight azure',
'midnight mint green',
'midnight forest green',
'midnight chartreuse',
'midnight khaki',
'midnight ivory',
'midnight mauve',
'midnight lilac',
'midnight plum',
'midnight fuchsia',
'midnight hot pink',
'midnight crimson',
'midnight slate gray',
'midnight steel blue',
'midnight olive green',
'midnight tomato',
'midnight dark cyan',
'midnight dark slate blue',
'midnight dark slate gray',
'midnight dark salmon',
'midnight dark magenta',
'midnight dark violet',
'midnight dark orchid',
'midnight dark turquoise',
'midnight dark olive green',
'midnight dark sea green',
'midnight dark khaki',
'midnight dark goldenrod',
'midnight dark orange',]

    module.exports = colorsArray